### ISSUE TITLE
Is Java 8 really needed? 

### ISSUE THREAD

**Issue by linean** [matomo-org/matomo-sdk-android#213]
What is the purpose of using Java 8 in this library? It requires from the developer to change Java compatibility for the whole project.

**Comment by d4rken** [comment]
> What is the purpose of using Java 8 in this library?

I wanted to use Java8 features such as lambdas within the library code.

> It requires from the developer to change Java compatibility for the whole project.

[Since AS 3.0](Since AS 3.0) native support exists for Java8 features. What's the downside?

**Comment by linean** [comment]
Much longer build time is the downside, especially if you are working on a big project.

**Comment by d4rken** [comment]
I can't say that I did any accurate measurements but I've not noticed any significant slow down when building an 80k LOC project (neither did a quick google search turn up any such issues). Can you point me to a resource with details on this?

> As I can see there is only one lambda in this code...

In tests too. Possibly also some multicatch and try+release.

**Comment by d4rken** [comment]
> I'm still thinking that library should not require this kind of changes :)

I agree that it's uncommon, but at somepoint I think it's okay to force this change, otherwise we'd still make libraries with a minAPI of 1.

> Maybe rewriting this tests in Kotlin will be good solution for that?

A good solution for what?

**Comment by linean** [comment]
> A good solution for what?

In Kotlin you can use lambdas without Java 8.

**Comment by d4rken** [comment]
I don't think introducing Kotlin to this project just for that is a good idea unless we rewrite the whole project in Kotlin which is superfluos.

I care less about it than it seems to bother you, so if you submit a PR that refactors the java8 use out of the code, then I think we can merge that for the next release.
