### ISSUE TITLE
EcommerceItems.Item price field is Integer.

### ISSUE THREAD

**Issue by taranTR** [matomo-org/matomo-sdk-android#242]
EcommerceItems.Item price field is Integer.I need to set Float value.
It should be Float,am i wrong?

**Comment by d4rken** [comment]
We are saving it as `if (mPrice != null) item.put(CurrencyFormatter.priceString(mPrice));` string?

Documentation says it should be float value though, so `10.00` and we seem to be sending `"10.00"`.

**Comment by taranTR** [comment]
i mean,sdk wants `int` as parameter from me and i cant give `float` value.Says `cent` in comment but it want `int`.
<img width="398" alt="ekran resmi 2019-01-15 21 51 30" src="https://user-images.githubusercontent.com/20425764/51202519-f78e1b00-190f-11e9-89e8-6f067e709684.png">

**Comment by d4rken** [comment]
On further investigation, it would only make sense to allow `float if we also change from using `cents` to whole $ or €, but this is something we can't easily do without breaking it for everyone currently using this.

So unless there is a really compelling reason to introduce this breaking change, it will stay as is.

**Comment by d4rken** [comment]
Reference:
https://matomo.org/docs/ecommerce-analytics/#example-tracking-an-ecommerce-order-containing-two-products

> price (parameter of addEcommerceItem() function), as well as grandTotal, subTotal, tax, shipping, discount (parameters of trackEcommerceOrder() function) must be supplied as integer or floats, not as string. For example, all the following values are not valid: “14.4$”, “EUR14.4”, “14,4”, “14.4”. The following values are valid: 5, 3.3, 5.44. If your Ecommerce software provides the values as string only, you can call the Javascript function parseFloat() after making sure the string does not contain currency symbol or other characters, for example: parseFloat(“554.20”). Note that the Javascript parseFloat() does not support comma separated decimal values “25,3” so you might have to replace the commas with dots before calling parseFloat().

**Comment by d4rken** [comment]
I'm preparing a PR that will add convenience methods to convert between cents and euros and also do some internal cleanup as the documentation says to not pass `string` which we currently do and although it seems to work we should keep close to the docs.

**Comment by taranTR** [comment]
i'm not using `string`,i just need set `float`.So now if i want to enter "2,53",i have to do  before "2,53*100" cause get as cent.And i'll send "253" right?Do I understand correctly?

**Comment by d4rken** [comment]
> i have to do before "2,53*100" cause get as cent.And i'll send "253" right?Do I understand correctly?

Yes :+1:

**Comment by taranTR** [comment]
Ok thank you.

**Comment by d4rken** [comment]
> I'm preparing a PR that will add convenience methods to convert between cents and euros and also do some internal cleanup as the documentation says to not pass string which we currently do and although it seems to work we should keep close to the docs.

I was on the wrong path here, due to passing the data to the api via e.g. url encoding we pass everything as *string* internally changing this in the SDK would be cool, but due to the breaking changes not worth it.
