### ISSUE TITLE
price showing "0" if price setted more than "999" 

### ISSUE THREAD

**Issue by taranTR** [matomo-org/matomo-sdk-android#243]
if i set price below "1000", everythings normal.

the result showing normal ->
<img width="294" alt="ekran resmi 2019-01-17 17 53 40" src="https://user-images.githubusercontent.com/20425764/51327141-b61d7d00-1a81-11e9-80d0-5a1271c8e1a5.png">

But if i set price more than "999"
<img width="254" alt="ekran resmi 2019-01-17 17 55 22" src="https://user-images.githubusercontent.com/20425764/51327214-e107d100-1a81-11e9-9fc3-554a7c0ea86d.png">

Sdk formatter result->
<img width="618" alt="ekran resmi 2019-01-17 17 56 47" src="https://user-images.githubusercontent.com/20425764/51327240-ee24c000-1a81-11e9-8c0b-7c1c35cbc76f.png">

the result showing "0"

<img width="384" alt="ekran resmi 2019-01-17 17 57 38" src="https://user-images.githubusercontent.com/20425764/51327265-00066300-1a82-11e9-95a8-aa26e8edb1b0.png">

Looking `,` is problem when parsing.

**Comment by d4rken** [comment]
I've release v4.0.2 with the fix. Good find :heart:
