### ISSUE TITLE
Cant create new tracker ?

### ISSUE THREAD

**Issue by royalhacker** [matomo-org/matomo-sdk-android#248]
how to create new tracker from trackerBuilder. Trackerbuilder.build asks for matomo which has private access. Please can somebody give a rough idea how to create new tracker.

**Comment by d4rken** [comment]
```java
new TrackerBuilder("https://demo.matomo.org/matomo.php", 53, "mytrackername").build(Matomo.getInstance(getApplicationContext()))
```

**Comment by brahyam** [comment]
Hey guys thanks for the hard work,

I believe this should be added to the docs for people not extending Matomo app
