### ISSUE TITLE
Tracking Content?

### ISSUE THREAD

**Issue by qstuff** [matomo-org/matomo-sdk-android#253]
Is this SDK capable of Content Tracking? It's mentioned that the API is capable of, but i did not find a method or more documentation on how to do it with the Android SDK.
I found a PR from 2014 which added this feature, but looks like it has gone in the meantime
https://github.com/matomo-org/matomo-sdk-android/pull/8/files

**Comment by d4rken** [comment]
This was just moved:

https://github.com/matomo-org/matomo-sdk-android/blob/master/tracker/src/main/java/org/matomo/sdk/extra/TrackHelper.java#L477

In any case the SDK always supports setting the key/values yourself, e.g. see `TrackMe` objects.

**Comment by qstuff** [comment]
it's a bit hidden ;) but thanks for the help.

**Comment by d4rken** [comment]
`Tracker` is the base class for all mechanics, while `TrackHelper` offers builder patterns to help you with the creation of `TrackMe` objects for all common use-cases.
