### ISSUE TITLE
unavailable SDK

### ISSUE THREAD

**Issue by sxf141** [matomo-org/matomo-sdk-android#254]
The request cannot be sent to the server, nor can Fiddler display the request.

org.matomo.sdk:tracker:4.0.2

public class BaseApplication extends MatomoApplication {
    private static BaseComponent mBaseComponent;
    private static BaseApplication mApplication;

    @Override
    public void onCreate() {
        super.onCreate();
        mApplication = this;
    }
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(base);
    }

    @Override
    public TrackerBuilder onCreateTrackerConfig() {
        return TrackerBuilder.createDefault(UrlConstant.PIWIK, 1);
    }

**Comment by d4rken** [comment]
lack of info
