### ISSUE TITLE
Android SDK takes more time to sync the details.

### ISSUE THREAD

**Issue by Nithiyasabariswaran** [matomo-org/matomo-sdk-android#263]
Android SDK takes more time to get reflect the screens and events in portal.

There is any configuration we need to set up?

Please advise,

Thanks

**Comment by d4rken** [comment]
`[Tracker.dispatch()](https://github.com/matomo-org/matomo-sdk-android/blob/master/tracker/src/main/java/org/matomo/sdk/Tracker.java#L204)`?

By default, events are batched and transmitted every 2 minutes or when the app is no longer on screen.

**Comment by Nithiyasabariswaran** [comment]
Hi,
Thanks.

After some event if i killed my APP what will happend?

**Comment by d4rken** [comment]
The events will be part of the next dispatch when the app is used again.

**Comment by d4rken** [comment]
Stale
