### ISSUE TITLE
Blocked by Play Protect

### ISSUE THREAD

**Issue by OMARIHAMZA** [matomo-org/matomo-sdk-android#264]
After integrating this sdk with my android project, "Blocked by Play Protect" dialog is shown when trying to install a signed APK.
Is there any solution for this problem?

![LlLiX](https://user-images.githubusercontent.com/36658089/64117435-e100db00-cd9d-11e9-9313-91af93f2a559.png)

**Comment by d4rken** [comment]
I don't think it's related. Your addition of the SDK was likely just coincidental.

The message talks about not recognizing the developer which is usually done via signing key, so you might have used the wrong signing key or have not used that key before such that it is unknown to Google Play "Protect".

**Comment by OMARIHAMZA** [comment]
> I don't think it's related. Your addition of the SDK was likely just coincidental.
> 
> The message talks about not recognizing the developer which is usually done via signing key, so you might have used the wrong signing key or have not used that key before such that it is unknown to Google Play "Protect".

I forgot to mention in the description that I removed the library and commented out the tracking code, signed the APK with the same keystore, and then installed the apk without any Play Protect warning.

**Comment by d4rken** [comment]
And if you now add the library again, uncomment the tracking code and sign the APK with the same keystore?

**Comment by OMARIHAMZA** [comment]
It seems that the issue was a problem with keystore used to sign the apk.
Thanks for your reply!
