### ISSUE TITLE
Best practice to track install referrer

### ISSUE THREAD

**Issue by AlexMisiulia** [matomo-org/matomo-sdk-android#265]
Hi!
Globally: I need to track install referrer for cases when user download application with URL using campaign details ( for example https://play.google.com/store/apps/details?id=com.mypackage&referrer=utm_source%3Dmobisoc%26utm_content%3D{transaction_id}%26utm_campaign%3D1). I think that matomo has built-in functionality for tracking this but I didn't found any information about it in docs or code.

UPD: I found a class `InstallReferrerReceiver`, seems that it saves referrer information in Preferences, and in  `DownloadTracker` it sends this information as `urlref` param.

Am I right? Is it a proper solution for this problem?

**Comment by d4rken** [comment]
Yes that's the idea.

Here is some more information on this topic:
https://stackoverflow.com/questions/30103338/android-is-it-possible-to-get-install-referrer-programmatically

You can test this locally by faking the broadcast via ADB.

**Comment by AlexMisiulia** [comment]
@d4rken thank you for the fast answer!
