### ISSUE TITLE
Custom dimensions event scope, user scope.

### ISSUE THREAD

**Issue by AlexMisiulia** [matomo-org/matomo-sdk-android#267]
Hi, I have a few questions about custom dimensions and their scopes.

Can I add custom variables to events (similar to [Amplitude](https://help.amplitude.com/hc/en-us/articles/207108327-Step-4-Set-User-Properties-and-Event-Properties#event-properties))?

I want to track some specific fields for the event. For example `email_error`, `name_error`, `password_error` for login events in order to track the frequency of these errors. What is the best way to do it in Matomo? Should I use a "Scope Page" or just add these fields as String to the label and then filter by regexp in Admin Panel?

What is the best practice to store "User Scope" variables?

When user logs in I want to track that he is authorized and his balance. When he logs out I want to reset these variables. But I guess that at admin panel visit variables will be cleared (because user logged out). Is it a right way to achieve it? Or maybe I should look at the "Scope Page" variables and add user information there for every screen event?

Thanks!

**Comment by AlexMisiulia** [comment]
UPD: I found that there is a possibility to track this event with the help of a custom [dimensions plugin](https://matomo.org/docs/custom-dimensions/). But I didn't find any way to send event dimensions (only screen).

**Comment by d4rken** [comment]
The `TrackHelper` class should have methods to supply custom dimensions along with screen views.
