### ISSUE TITLE
No datas receive to matomo cloud

### ISSUE THREAD

**Issue by RomainDev25** [matomo-org/matomo-sdk-android#268]
Hello, before install matomo in our server, we want to test on matomo cloud, it's more simple.

I take Example application in this repo, change in DemoApp.java
Url and Siteid

I receive datas on time, and after nothing
In logcat, I have this, so for me it's ok : I/DemoApp: Tracker.Callback.onTrack(org.matomo.sdk.TrackMe@80855c7)

What I need to params in settings application to send to Server ?

It's possible to enable more log ?
I try to enable this getMatomo().setDryRun(BuildConfig.DEBUG);
Buy I have this issue cannot resolve setDryRun method

Thanks in advance.

Romain

**Comment by Findus23** [comment]
> I receive datas on time, and after nothing

Can you check in Matomo if you are seeing any data in the visitor log?
All other reports might be slightly delayed as they need to be generated.

**Comment by RomainDev25** [comment]
In visits log, I have datas at 12:04 and after this nothing.
In example application I have set dispatch interval 0
Session timeout 30
Dry run unchecked
Opt out unchecked

**Comment by RomainDev25** [comment]
Ok, it's me I have don't see fetched is at 120000 secondes each time we recompile app.
Datas arrive.
Thank you ;)
