### ISSUE TITLE
Don't send ip adress RGPD

### ISSUE THREAD

**Issue by RomainDev25** [matomo-org/matomo-sdk-android#269]
Hello, I have a question, I want to don't send ip adress of visitor if he don't send consentement.
It's possible to send screen and disable send of ip adress ?
Have a nice day.
Romain

**Comment by RomainDev25** [comment]
Ok thank you for the answer, so if we install our server, we can catch this.
We send variable with no ip for example and in server, we remove ip of user.
It's possible to develop module or not ?
Have a nice day.

**Comment by d4rken** [comment]
Client IP obfuscation is a server-side feature and requires no configuration within the Android-SDK.
