### ISSUE TITLE
Matomo analytics not showing data on admin panel in android

### ISSUE THREAD

**Issue by AbhijeetDandiwal** [matomo-org/matomo-sdk-android#270]
Hello Team,

We are working on Matomo analytics integration in android application.
Below is the sdk we have used :-
a. ) implementation group: 'org.matomo.sdk', name: 'tracker', version: '4.1.0'

And we used below code :- 
MainActivity.java

 Tracker tracker = ((MatomoApplication) getApplication()).getTracker();
 TrackHelper.track().screen("/java/com.example.matomo/MainActivity").title("Yipee").with(tracker);
 TrackHelper.track().goal(2).with(tracker);
TrackHelper.track().download().with(tracker);

**************************************************
App.Java
In public class App extends MatomoApplication{
 @Override
    public TrackerBuilder onCreateTrackerConfig() {
        return TrackerBuilder.createDefault("https://******.com/matomo/index.php?", 2);
    }
}
***************************************************
In Menifest added below line:
 android:name=".App"
*******************************************
After doing so, we are unable to track user activities. Please help us ASAP.

Thanks & Regards,
Abhijeet Singh.

**Comment by Ponsen** [comment]
Hi,

I'm having a similar issue. I've updated from piwik 2.X to Matomo 4.1.0 and couldn't see any entries in matomo backend (3.13.0). Android Studio Profiler shows the requests are working with reponse code 200 but nothing in the backend. I've just tested downgrading to piwik 3.0.3 and it's working again. During the tests with 4.1.0 i've activated the matomo logs, but it wasn't loggin any 4.1.0 requests.

Any suggestions?

**Comment by d4rken** [comment]
Have you checked the v3 -> v4 hints?

https://github.com/matomo-org/matomo-sdk-android/wiki/Migration#v30-to-v40

I think you most likely need to correct the URL, and append either `piwik.php` or `matomo.php` which was previously done by the SDK.

**Comment by Ponsen** [comment]
I must have missed that. It's working now.
Thank you very much.
