### ISSUE TITLE
Error in Quickstart

### ISSUE THREAD

**Issue by moopat** [matomo-org/matomo-sdk-android#282]
The simple tracking example in the [README](https://github.com/matomo-org/matomo-sdk-android#quickstart) does not work, because `TrackerBuilder.createDefault()` returns an instance of `TrackerBuilder`, not `Tracker`.

```
public synchronized Tracker getTracker() {
    if (tracker == null) tracker = TrackerBuilder.createDefault("http://domain.tld/matomo.php", 1);
    return tracker;
}
```

**Comment by d4rken** [comment]
Oh, can you submit a PR?

**Comment by moopat** [comment]
Sure.
