### ISSUE TITLE
Activate Logging

### ISSUE THREAD

**Issue by userdimi** [matomo-org/matomo-sdk-android#288]
Hey guys,

I've implemented the Matomo tracking library in my project like described in the documentation but for some reason I don't receive any events on my server. So my question is, is there a possibility to activate logging in the SDK so I can see that my client configuration is setup correct and the events are sent to the server?

**Comment by d4rken** [comment]
The library internally logs via `Timber`, you can enable logging by planting a debug tree, see:

https://github.com/matomo-org/matomo-sdk-android/blob/master/exampleapp/src/main/java/org/matomo/demo/DemoApp.java#L41

**Comment by userdimi** [comment]
Ok, works thank you. Would be nice if this would be a part of the documentation.

**Comment by chrisvire** [comment]
For Java users, here is a link to older Java version:

https://github.com/matomo-org/matomo-sdk-android/blob/a2bdc186dc6c06e9f6961383cd8565a5b7a1bc5b/exampleapp/src/main/java/org/matomo/demo/DemoApp.java

For Kotlin, look at the recent Demo.kt:

https://github.com/matomo-org/matomo-sdk-android/blob/master/exampleapp/src/main/java/org/matomo/demo/DemoApp.kt
