### ISSUE TITLE
Migration to mavenCentral()

### ISSUE THREAD

**Issue by abhishekBansal** [matomo-org/matomo-sdk-android#301]
As `JCenter` has [decided to drop curtains](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on its services, are there any plans to move to `mavenCentral()` in near future?

**Comment by diosmosis** [comment]
Hi @abhishekBansal, this repository is currently unmaintained so unfortunately that's not something that's planned. We are currently looking for a maintainer, however. If you're interested, feel free to get in touch.

**Comment by JJSarrasin** [comment]
Same here, by using Gradle 7.0, it displayed a big warning saying Jcenter is already shutdown and the jcenter() support in AS will be removed with gradle 8.0

The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's shutdown in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#jcenter_deprecation

**Comment by hannesa2** [comment]
When I remove `jcenter()` by 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/3314607/120097157-3f075180-c12f-11eb-865b-be0bd3008764.png">

I run into
```
   > Could not find org.matomo.sdk:tracker:4.1.2.
     Required by:
         project :app > project :commonLib
```

But there is a easy solution https://jitpack.io/#matomo-org/matomo-sdk-android/v4.1.2

	allprojects {
	  repositories {
	    ...
	    maven { url 'https://jitpack.io' }
	  }
	}

and

	dependencies {
	  implementation 'com.github.matomo-org:matomo-sdk-android:v4.1.2'
	}

**Comment by d4rken** [comment]
I'll leave this open as the final goal would be to setup mavenCentral, but for now we can remove jcenter and go with JitPack.

**Comment by jaypi95** [comment]
The URL in the quick start part of the README should be updated too to `com.github.matomo-org:matomo-sdk-android` instead of `org.matomo.sdk:tracker`

Same for the part in the wiki.

**Comment by d4rken** [comment]
Thanks, fixed.
