### ISSUE TITLE
Single session with actions from multiple visitor ids

### ISSUE THREAD

**Issue by ColeKainz** [matomo-org/matomo-sdk-android#320]
Hey all.

My company seeing sessions with actions from multiple visitors stitched together. 
Basically, I see action from user 1 -> action from user two -> action from user 1.  

The users have different user and visitor IDs, in many cases user 1 has no user ID. I noticed [this](https://github.com/matomo-org/matomo-sdk-android/issues/259) thread discussing visit stitching (d4rken's second comment). Could this be what I'm running in to?

Through the Matomo portal I only see one vistor ID per session, despite actions from different users existing in the session. When querying the data through the Matomo API, each user in a session has a different visitor ID.

As far as I know these users have nothing to do with each other, other then when they opened the app. These sessions seem to have users who opened the app around the same time, so Matomo may be resolving them to the same visit ID? This is just a guess, and if this is true it doesn't happen consistently at all (this hasn't happened in our development Matomo server, where QA is switching between testing accounts all the time). 

Any thoughts?

**Comment by ColeKainz** [comment]
This is in the way of my company's business objectives. Does someone want to meet up in a live chat (telegram) to discuss this?

**Comment by d4rken** [comment]
If this is business critical, consider [enterprise support](https://matomo.org/enterprise-analytics/).

**Comment by ColeKainz** [comment]
I'll look into it, thanks.
