### ISSUE TITLE
Documentation: dead links

### ISSUE THREAD

**Issue by heurteph-ei** [matomo-org/matomo-sdk-android#322]
Page/Chapiter: https://github.com/matomo-org/matomo-sdk-android/wiki/Getting-started#basic
>**Basic**
>You can simply have your application extend our [MatomoApplication](https://github.com/matomo/matomo-sdk-android/blob/master/matomo-sdk/src/main/java/org/matomo/sdk/MatomoApplication.java) class. You will be forced to implement a few abstract methods. [This approach is used](https://github.com/matomo/matomo-sdk-android/blob/master/exampleapp/src/main/java/com/matomo/demo/DemoApp.java) in our demo app.

Both links are dead

I think all internal links in the page are dead...

**Comment by d4rken** [comment]
Hm seems that links point to `/matomo` while the actual URL is `/matomo-org` :thinking:

**Comment by d4rken** [comment]
Updated the docs.
