### ISSUE TITLE
Flaky unit test `testDispatchRetryWithBackoff`

### ISSUE THREAD

**Issue by d4rken** [matomo-org/matomo-sdk-android#363]
From #362:

https://github.com/matomo-org/matomo-sdk-android/runs/7577661791?check_suite_focus=true#step:5:162

```java
> Task :tracker:testDebugUnitTest

org.matomo.sdk.dispatcher.DefaultDispatcherTest > testDispatchRetryWithBackoff FAILED
    org.awaitility.core.ConditionTimeoutException at DefaultDispatcherTest.java:372

226 tests completed, 1 failed
```

Passed on second run.

**Comment by hannesa2** [comment]
I never run into this 
https://github.com/matomo-org/matomo-sdk-android/actions/workflows/pull-request-ci.yml

I guess we can close it
