### ISSUE TITLE
Test new release pipeline

### ISSUE THREAD

**Issue by hannesa2** [matomo-org/matomo-sdk-android#379]
@d4rken 
Just to let you know, I made an automated created pre-release https://github.com/matomo-org/matomo-sdk-android/releases/tag/4.2-beta1 by setting just a `beta` in tag name to see if it works

**Comment by hannesa2** [comment]
In my point of view we could create a `4.2` now

**Comment by d4rken** [comment]
> In my point of view we could create a `4.2` now

Fine with me, go a head :+1:
