### ISSUE TITLE
Add license information to pom file 

### ISSUE THREAD

**Issue by ptrkaz** [matomo-org/matomo-sdk-android#503]
Currently, the resulting pom.xml file of the library is missing information about the license, which leads to issues when using tools that would benefit from retrieving that information. 

It would be great if license info could be added to the file. 
One approach could be to add the `pom {}` block to `mavenPublish` in gradle.

**Comment by hannesa2** [comment]
please see https://github.com/matomo-org/matomo-sdk-android/pull/504

**Comment by ptrkaz** [comment]
Wow, thanks for looking into that so quickly!
